services: # represente une image
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    volumes: 
      - mariadb_database:/var/lib/mysql
    networks:
      - network
    environment:
      MARIA_PASSWORD: /run/secrets/db_password
      MARIA_ROOT_PASSWORD: /run/secrets/db_root_password
      # pour attribuer a des variable les valeur contenue dans .env
    # depends_on: nginx
    # command
    restart: on-failure
    secrets:
      - db_password
      - db_root_password
    # toujours mettre des guillemets  pour appeller les variables du .env

  
  nginx:
    build: ./requirements/nginx
    image: nginx
    networks:
      - network
    # ports :
    # depends_on
    # command
    # environment
    # healthcheck
    restart: on-failure
    # secrets
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes: 
      - wp_website_files:/var/www/html
    networks:
      - network
    # depends_on: nginx & mariadb?
    # command
    # environment
    # healthcheck
    restart: on-failure
    # secrets

volumes:
  # bind mount
  mariadb_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/login/data/mariadb
  
  wp_website_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/login/data/wordpress

networks:
  network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  credentials:
    file: ./secrets/credentials

  


